language: python

matrix:
  include:
    - python: 3.4
      env:
        - COVERAGE=false
    - python: 3.5
      env:
        - COVERAGE=false
    - python: 3.6
      env:
        - COVERAGE=true
    - python: 3.7
      env:
        - COVERAGE=false

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda update --yes conda
  - conda install --yes nomkl


install:
  - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION scipy seaborn coverage docopt requests pyyaml pytest pytest-mpl pytest-cov --channel=conda-forge
  - source activate test
  - pip install coveralls
  - pip install .

script:
  - coverage run --source paramnormal check_paramnormal.py --mpl --verbose

after_success:
  - if [ ${COVERAGE} = true ]; then
      coverage report -m;
      coveralls;
    fi

