package:
  name: paramnormal
  version: 0.4.3

source:
  git_url: https://github.com/phobson/paramnormal.git
  git_tag: v0.4.3

build:
  number: 1
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - nose

test:
  imports:
    - paramnormal

  commands:
    - python -c "import paramnormal; paramnormal.test()"

  requires:
    - nose

about:
  home: http://phobson.github.io/paramnormal/
  license:  BSD License
  summary: 'Conventionally parameterized probability distributions.'

