name: Run coverage via codecov
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Generate coverage report
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements_dev.txt ]; then pip install -r requirements_dev.txt; fi
        coverage run --source paramnormal check_paramnormal.py --doctest-modules --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        # directory: ./coverage/reports/
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
        path_to_write_report: ./codecov_report.gz
